Setting the initial env
addnull/raynor pull request #1
Opened 2016-09-27 10:39 UTC by mingrammer

Setting the initial environments

2016-09-27 12:28 UTC, mingrammer commented
@addnull Please review

2016-09-28 05:36 UTC, addnull requested changes

2016-09-28 05:36 UTC, addnull commented on .gitignore
> +dist/
하위 폴더를 모두 포함해서 git ignore할게 아니라면 '/dist/' 식으로 앞에 '/'를 붙여주는게 좋습니다.

2016-09-28 05:38 UTC, mingrammer commented on .gitignore
> +dist/
모두 ignore합니다

2016-09-28 06:20 UTC, mingrammer commented on .gitignore
> +dist/
.gitignore는 https://github.com/django/django/blob/master/.gitignore 를 참고하였습니다.

2016-09-28 10:27 UTC, mingrammer commented on .gitignore
> +dist/
Update .gitignore

2016-09-28 11:04 UTC, addnull approved these changes

2016-09-28 11:04 UTC, merged